### ISSUE TITLE
thinger_client.h

### ISSUE THREAD

**Issue by jeze519** [thinger-io/Linux-Client#2]
Update the thinger_client.h file to have the below code to main.cpp can get #define THINGER_SERVER 
#ifndef THINGER_SERVER
#define THINGER_SERVER
#endif

Did this already on an install for monitoring the local server install of thinger.

**Comment by bautisflow** [comment]
Hi @jeze519,

First of all thank you for the input. As of today this issue has been resolved.
Please let us know if you have any other issue.

Regards.
